const CARD = {
  COUNT: 18,
  RATIO: 2.5 / 3.5,
  CORNERS_WIDTH_RATIO: 1 / 20,
  ANIMATIONS: {
    FLIP: 700,
    SHAKE: 600,
    START_SHAKE_EAGER_MS: 250,
    START_SHAKE_AFTER_RETURN_PERCENT_COMPLETE: 0.75,
    SHUFFLE_PAUSE: 50,
    SHUFFLE_ACTIVE: 350,
    SHAKE_DELAY_AFTER_STARTING_RETURN: 0,
    HIDE_UNDERSIDE_AFTER_RETURN_PERCENT_COMPLETE: 0.9,
    FLIP_DELAYED_OFF: 250,
  },
};

CARD.ANIMATIONS.SHAKE_DELAY_AFTER_STARTING_RETURN =
  CARD.ANIMATIONS.FLIP *
    CARD.ANIMATIONS.START_SHAKE_AFTER_RETURN_PERCENT_COMPLETE -
  CARD.ANIMATIONS.START_SHAKE_EAGER_MS;

const GAME = {
  AUTO: {
    PAUSE_DELAY_MS: 10 * 1000,
    SHUFFLE_DELAY: 10 * 1000,
    SHUFFLE_INTERVAL: 10 * 1000,
  },

  BOARD_PADDING_PERCENT: 1.5,
  HASH_LENGTH_BYTES: 32,

  MINIMUM_TIME_BETWEEN_CLICKS: 500,

  SHUFFLE_ROUNDS: 5,
  SUCCESS_COUNTER_ANIMATE_DURATION: 400,
  MISMATCH_COUNTER_ANIMATE_DURATION: 0,
};

GAME.MISMATCH_COUNTER_ANIMATE_DURATION = GAME.SUCCESS_COUNTER_ANIMATE_DURATION;

const CONSTANTS = {
  CARD,
  GAME,
}

export default CONSTANTS;
