const CARD_RATIO = 2.5 / 3.5; // w / h
const CORNERS_WIDTH_RATIO = 1 / 20;

const AUTO_PAUSE_DELAY_MS = 10000;

const CARD_FLIP_ANIMATION_DURATION = 700;
const CARD_SHAKE_ANIMATION_DURATION = 600;

// after initial instant transform, wait this long before starting animation
const CARD_SHUFFLE_PAUSE_DURATION = 50;
// animation duration
const CARD_SHUFFLE_ACTIVE_DURATION = 350;

const MINIMUM_TIME_BETWEEN_CLICKS = 500;
const CARD_RATIO_VS_CONTAINER = 0.9;

export const BOARD = {
  CARD_RATIO,
  CORNERS_WIDTH_RATIO,
  AUTO_PAUSE_DELAY_MS,
  CARD_FLIP_ANIMATION_DURATION,
  CARD_SHAKE_ANIMATION_DURATION,
  CARD_SHUFFLE_PAUSE_DURATION,
  CARD_SHUFFLE_ACTIVE_DURATION,
  MINIMUM_TIME_BETWEEN_CLICKS,
  CARD_RATIO_VS_CONTAINER,
}
