import { BOARD } from "./board";

const AUTO_SHUFFLE_INTERVAL = 10000;
const AUTO_SHUFFLE_DELAY = 10000;

const CARD_SHUFFLE_ROUNDS = 5;

// higher means shake starts sooner
const START_SHAKE_ANIMATION_EAGER_MS = 250;
const START_SHAKE_WHEN_FLIP_DOWN_IS_PERCENT_COMPLETE = 0.75;
const SHAKE_ANIMATION_DELAY_AFTER_STARTING_TO_RETURN_TO_BOARD =
  BOARD.CARD_FLIP_ANIMATION_DURATION *
    START_SHAKE_WHEN_FLIP_DOWN_IS_PERCENT_COMPLETE -
  START_SHAKE_ANIMATION_EAGER_MS;

const DEFAULT_CARD_COUNT = 18;

const CONTAINER_PADDING_PERCENT = 1.5;
const MIN_CARD_COUNT = 6;
const MAX_CARD_COUNT = 52;

export const GAME = {
  AUTO_SHUFFLE_INTERVAL,
  AUTO_SHUFFLE_DELAY,
  CARD_SHUFFLE_ROUNDS,
  START_SHAKE_ANIMATION_EAGER_MS,
  START_SHAKE_WHEN_FLIP_DOWN_IS_PERCENT_COMPLETE,
  SHAKE_ANIMATION_DELAY_AFTER_STARTING_TO_RETURN_TO_BOARD,
  DEFAULT_CARD_COUNT,
  CONTAINER_PADDING_PERCENT,
  MIN_CARD_COUNT,
  MAX_CARD_COUNT,
};
