export const formattedDeck = [
  {
    id: 940760,
    text: "AD",
    pairId: 940761,
    position: 0,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/aceDiamonds.png",
  },
  {
    id: 940761,
    text: "AH",
    pairId: 940760,
    position: 1,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/AH.png",
  },
  {
    id: 309810,
    text: "AC",
    pairId: 309811,
    position: 2,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/AC.png",
  },
  {
    id: 309811,
    text: "AS",
    pairId: 309810,
    position: 3,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/AS.png",
  },
  {
    id: 145490,
    text: "2D",
    pairId: 145491,
    position: 4,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/2D.png",
  },
  {
    id: 145491,
    text: "2H",
    pairId: 145490,
    position: 5,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/2H.png",
  },
  {
    id: 190270,
    text: "2C",
    pairId: 190271,
    position: 6,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/2C.png",
  },
  {
    id: 190271,
    text: "2S",
    pairId: 190270,
    position: 7,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/2S.png",
  },
  {
    id: 735020,
    text: "3D",
    pairId: 735021,
    position: 8,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/3D.png",
  },
  {
    id: 735021,
    text: "3H",
    pairId: 735020,
    position: 9,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/3H.png",
  },
  {
    id: 890610,
    text: "3C",
    pairId: 890611,
    position: 10,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/3C.png",
  },
  {
    id: 890611,
    text: "3S",
    pairId: 890610,
    position: 11,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/3S.png",
  },
  {
    id: 712320,
    text: "4D",
    pairId: 712321,
    position: 12,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/4D.png",
  },
  {
    id: 712321,
    text: "4H",
    pairId: 712320,
    position: 13,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/4H.png",
  },
  {
    id: 979860,
    text: "4C",
    pairId: 979861,
    position: 14,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/4C.png",
  },
  {
    id: 979861,
    text: "4S",
    pairId: 979860,
    position: 15,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/4S.png",
  },
  {
    id: 774670,
    text: "5D",
    pairId: 774671,
    position: 16,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/5D.png",
  },
  {
    id: 774671,
    text: "5H",
    pairId: 774670,
    position: 17,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/5H.png",
  },
  {
    id: 991980,
    text: "5C",
    pairId: 991981,
    position: 18,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/5C.png",
  },
  {
    id: 991981,
    text: "5S",
    pairId: 991980,
    position: 19,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/5S.png",
  },
  {
    id: 325890,
    text: "6D",
    pairId: 325891,
    position: 20,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/6D.png",
  },
  {
    id: 325891,
    text: "6H",
    pairId: 325890,
    position: 21,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/6H.png",
  },
  {
    id: 590610,
    text: "6C",
    pairId: 590611,
    position: 22,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/6C.png",
  },
  {
    id: 590611,
    text: "6S",
    pairId: 590610,
    position: 23,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/6S.png",
  },
  {
    id: 215990,
    text: "7D",
    pairId: 215991,
    position: 24,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/7D.png",
  },
  {
    id: 215991,
    text: "7H",
    pairId: 215990,
    position: 25,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/7H.png",
  },
  {
    id: 615530,
    text: "7C",
    pairId: 615531,
    position: 26,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/7C.png",
  },
  {
    id: 615531,
    text: "7S",
    pairId: 615530,
    position: 27,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/7S.png",
  },
  {
    id: 173730,
    text: "8D",
    pairId: 173731,
    position: 28,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/8D.png",
  },
  {
    id: 173731,
    text: "8H",
    pairId: 173730,
    position: 29,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/8H.png",
  },
  {
    id: 476300,
    text: "8C",
    pairId: 476301,
    position: 30,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/8C.png",
  },
  {
    id: 476301,
    text: "8S",
    pairId: 476300,
    position: 31,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/8S.png",
  },
  {
    id: 118260,
    text: "9D",
    pairId: 118261,
    position: 32,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/9D.png",
  },
  {
    id: 118261,
    text: "9H",
    pairId: 118260,
    position: 33,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/9H.png",
  },
  {
    id: 339380,
    text: "9C",
    pairId: 339381,
    position: 34,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/9C.png",
  },
  {
    id: 339381,
    text: "9S",
    pairId: 339380,
    position: 35,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/9S.png",
  },
  {
    id: 603560,
    text: "0D",
    pairId: 603561,
    position: 36,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/0D.png",
  },
  {
    id: 603561,
    text: "0H",
    pairId: 603560,
    position: 37,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/0H.png",
  },
  {
    id: 860980,
    text: "0C",
    pairId: 860981,
    position: 38,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/0C.png",
  },
  {
    id: 860981,
    text: "0S",
    pairId: 860980,
    position: 39,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/0S.png",
  },
  {
    id: 741820,
    text: "JD",
    pairId: 741821,
    position: 40,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/JD.png",
  },
  {
    id: 741821,
    text: "JH",
    pairId: 741820,
    position: 41,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/JH.png",
  },
  {
    id: 622610,
    text: "JC",
    pairId: 622611,
    position: 42,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/JC.png",
  },
  {
    id: 622611,
    text: "JS",
    pairId: 622610,
    position: 43,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/JS.png",
  },
  {
    id: 116660,
    text: "QD",
    pairId: 116661,
    position: 44,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/QD.png",
  },
  {
    id: 116661,
    text: "QH",
    pairId: 116660,
    position: 45,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/QH.png",
  },
  {
    id: 987380,
    text: "QC",
    pairId: 987381,
    position: 46,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/QC.png",
  },
  {
    id: 987381,
    text: "QS",
    pairId: 987380,
    position: 47,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/QS.png",
  },
  {
    id: 649980,
    text: "KD",
    pairId: 649981,
    position: 48,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/KD.png",
  },
  {
    id: 649981,
    text: "KH",
    pairId: 649980,
    position: 49,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/KH.png",
  },
  {
    id: 668400,
    text: "KC",
    pairId: 668401,
    position: 50,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/KC.png",
  },
  {
    id: 668401,
    text: "KS",
    pairId: 668400,
    position: 51,
    prevPosition: null,
    isMismatched: false,
    image: "https://deckofcardsapi.com/static/img/KS.png",
  },
];
