import { Score } from "~/v3/db/schemas/types";
import { generateRandomGameTimeDs, generateRandomMismatches } from "./seed";

export const createScores = (count: number = 10_000, _deckSize: number = 52) => {
  const initials = "";
  const userId = "";
  const createdAt = 123;
  const deckSize = _deckSize;
  const pairs = deckSize / 2;

  const scores: Score[] = new Array(count).fill(null).map((_, i) => ({
    id: i, // doesn't really matter for these tests
    createdAt,
    initials,
    userId,
    pairs,
    deckSize,
    // mismatches: i * 2,
    // gameTimeDs: i * 100,
    // mismatches: Math.floor(Math.random() * 11), // e.g. 0-10 mismatches
    // gameTimeDs: Math.floor(Math.random() * 1000), // e.g. 0-99.9 seconds or 0-999 decaseconds
    mismatches: generateRandomMismatches(deckSize),
    gameTimeDs: generateRandomGameTimeDs(deckSize),
  }));
  return scores;
};

// console.log({ scores10000: JSON.stringify(createScores(500).map(({mismatches, gameTimeDs}) => ({mm: mismatches, gt: gameTimeDs}))) });

type Key = "mismatches" | "gameTimeDs";

export const getScoresByKey = (scores: Score[], key: Key) => scores.reduce(
  (
    mappers: {
      scoresByKey: Record<number, number>;
      orderedListOfScoreIds: number[];
    },
    curScore,
  ) => {
    // organize by deckSize:
    if (!mappers.scoresByKey[curScore[key]]) {
      mappers.scoresByKey[curScore[key]] = 1;
    } else {
      mappers.scoresByKey[curScore[key]] += 1;
    }
    // maintain ID order
    mappers.orderedListOfScoreIds.push(curScore.id);
    return mappers;
  },
  { scoresByKey: {}, orderedListOfScoreIds: [] },
);

// const findWorst = (scores: Score[], key: Key) => scores
//   .reduce((lowest, score) => {
//     if (score[key] > lowest) {
//       return score[key];
//     }
//     return lowest;
//   }, -1);

const getCountForHighest = (scores: Score[], key: Key) => {
  const { scoresByKey } = getScoresByKey(scores, key);
  console.log({scoresByKey, key});
  const scoresEntries = Object.entries(scoresByKey);
  const countInScores = scoresEntries
    .reduce((total, [_, count]) => total += count, 0)
  console.log({countInScores});

  const countOfScoresThatRankedHighest = scoresEntries[0][1];
  return scores.length - (countInScores - countOfScoresThatRankedHighest);
}

export const scores100 = [
  {
    id: 0,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 0,
    gameTimeDs: 242,
  },
  {
    id: 1,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 8,
    gameTimeDs: 211,
  },
  {
    id: 2,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 1,
    gameTimeDs: 562,
  },
  {
    id: 3,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 8,
    gameTimeDs: 818,
  },
  {
    id: 4,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 6,
    gameTimeDs: 929,
  },
  {
    id: 5,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 5,
    gameTimeDs: 349,
  },
  {
    id: 6,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 0,
    gameTimeDs: 543,
  },
  {
    id: 7,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 6,
    gameTimeDs: 292,
  },
  {
    id: 8,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 7,
    gameTimeDs: 499,
  },
  {
    id: 9,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 9,
    gameTimeDs: 955,
  },
  {
    id: 10,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 0,
    gameTimeDs: 238,
  },
  {
    id: 11,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 5,
    gameTimeDs: 761,
  },
  {
    id: 12,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 7,
    gameTimeDs: 687,
  },
  {
    id: 13,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 7,
    gameTimeDs: 375,
  },
  {
    id: 14,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 4,
    gameTimeDs: 960,
  },
  {
    id: 15,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 3,
    gameTimeDs: 622,
  },
  {
    id: 16,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 8,
    gameTimeDs: 920,
  },
  {
    id: 17,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 3,
    gameTimeDs: 92,
  },
  {
    id: 18,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 1,
    gameTimeDs: 614,
  },
  {
    id: 19,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 4,
    gameTimeDs: 759,
  },
  {
    id: 20,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 5,
    gameTimeDs: 39,
  },
  {
    id: 21,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 9,
    gameTimeDs: 163,
  },
  {
    id: 22,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 5,
    gameTimeDs: 43,
  },
  {
    id: 23,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 9,
    gameTimeDs: 441,
  },
  {
    id: 24,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 3,
    gameTimeDs: 699,
  },
  {
    id: 25,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 1,
    gameTimeDs: 973,
  },
  {
    id: 26,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 10,
    gameTimeDs: 630,
  },
  {
    id: 27,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 1,
    gameTimeDs: 437,
  },
  {
    id: 28,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 8,
    gameTimeDs: 413,
  },
  {
    id: 29,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 2,
    gameTimeDs: 479,
  },
  {
    id: 30,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 10,
    gameTimeDs: 692,
  },
  {
    id: 31,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 0,
    gameTimeDs: 92,
  },
  {
    id: 32,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 10,
    gameTimeDs: 414,
  },
  {
    id: 33,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 8,
    gameTimeDs: 723,
  },
  {
    id: 34,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 5,
    gameTimeDs: 613,
  },
  {
    id: 35,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 8,
    gameTimeDs: 142,
  },
  {
    id: 36,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 6,
    gameTimeDs: 573,
  },
  {
    id: 37,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 6,
    gameTimeDs: 136,
  },
  {
    id: 38,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 2,
    gameTimeDs: 54,
  },
  {
    id: 39,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 4,
    gameTimeDs: 211,
  },
  {
    id: 40,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 4,
    gameTimeDs: 37,
  },
  {
    id: 41,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 10,
    gameTimeDs: 454,
  },
  {
    id: 42,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 8,
    gameTimeDs: 986,
  },
  {
    id: 43,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 6,
    gameTimeDs: 122,
  },
  {
    id: 44,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 1,
    gameTimeDs: 493,
  },
  {
    id: 45,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 2,
    gameTimeDs: 203,
  },
  {
    id: 46,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 9,
    gameTimeDs: 619,
  },
  {
    id: 47,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 9,
    gameTimeDs: 149,
  },
  {
    id: 48,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 8,
    gameTimeDs: 834,
  },
  {
    id: 49,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 6,
    gameTimeDs: 394,
  },
  {
    id: 50,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 2,
    gameTimeDs: 107,
  },
  {
    id: 51,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 3,
    gameTimeDs: 167,
  },
  {
    id: 52,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 9,
    gameTimeDs: 187,
  },
  {
    id: 53,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 6,
    gameTimeDs: 894,
  },
  {
    id: 54,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 1,
    gameTimeDs: 971,
  },
  {
    id: 55,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 10,
    gameTimeDs: 494,
  },
  {
    id: 56,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 1,
    gameTimeDs: 172,
  },
  {
    id: 57,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 2,
    gameTimeDs: 913,
  },
  {
    id: 58,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 0,
    gameTimeDs: 657,
  },
  {
    id: 59,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 0,
    gameTimeDs: 706,
  },
  {
    id: 60,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 8,
    gameTimeDs: 386,
  },
  {
    id: 61,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 10,
    gameTimeDs: 672,
  },
  {
    id: 62,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 5,
    gameTimeDs: 708,
  },
  {
    id: 63,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 0,
    gameTimeDs: 145,
  },
  {
    id: 64,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 1,
    gameTimeDs: 450,
  },
  {
    id: 65,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 10,
    gameTimeDs: 471,
  },
  {
    id: 66,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 3,
    gameTimeDs: 615,
  },
  {
    id: 67,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 10,
    gameTimeDs: 678,
  },
  {
    id: 68,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 0,
    gameTimeDs: 919,
  },
  {
    id: 69,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 7,
    gameTimeDs: 623,
  },
  {
    id: 70,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 5,
    gameTimeDs: 616,
  },
  {
    id: 71,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 3,
    gameTimeDs: 234,
  },
  {
    id: 72,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 9,
    gameTimeDs: 379,
  },
  {
    id: 73,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 7,
    gameTimeDs: 919,
  },
  {
    id: 74,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 8,
    gameTimeDs: 363,
  },
  {
    id: 75,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 3,
    gameTimeDs: 474,
  },
  {
    id: 76,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 7,
    gameTimeDs: 755,
  },
  {
    id: 77,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 7,
    gameTimeDs: 302,
  },
  {
    id: 78,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 9,
    gameTimeDs: 260,
  },
  {
    id: 79,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 10,
    gameTimeDs: 860,
  },
  {
    id: 80,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 0,
    gameTimeDs: 509,
  },
  {
    id: 81,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 6,
    gameTimeDs: 272,
  },
  {
    id: 82,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 8,
    gameTimeDs: 806,
  },
  {
    id: 83,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 2,
    gameTimeDs: 483,
  },
  {
    id: 84,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 0,
    gameTimeDs: 312,
  },
  {
    id: 85,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 5,
    gameTimeDs: 960,
  },
  {
    id: 86,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 9,
    gameTimeDs: 422,
  },
  {
    id: 87,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 0,
    gameTimeDs: 536,
  },
  {
    id: 88,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 7,
    gameTimeDs: 0,
  },
  {
    id: 89,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 10,
    gameTimeDs: 661,
  },
  {
    id: 90,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 4,
    gameTimeDs: 633,
  },
  {
    id: 91,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 8,
    gameTimeDs: 832,
  },
  {
    id: 92,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 4,
    gameTimeDs: 544,
  },
  {
    id: 93,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 0,
    gameTimeDs: 256,
  },
  {
    id: 94,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 5,
    gameTimeDs: 631,
  },
  {
    id: 95,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 3,
    gameTimeDs: 302,
  },
  {
    id: 96,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 4,
    gameTimeDs: 270,
  },
  {
    id: 97,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 7,
    gameTimeDs: 337,
  },
  {
    id: 98,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 0,
    gameTimeDs: 134,
  },
  {
    id: 99,
    createdAt: 123,
    initials: "",
    userId: "",
    pairs: 9,
    deckSize: 18,
    mismatches: 1,
    gameTimeDs: 361,
  },
];
